require "multi_xml"

require "picasa/version"
require "picasa/utils"
require "picasa/exceptions"
require "picasa/http"
require "picasa/connection"
require "picasa/client"
require "picasa/file"
require "picasa/template"

require "picasa/api/album"
require "picasa/api/comment"
require "picasa/api/photo"
require "picasa/api/tag"

require "picasa/presenter/album"
require "picasa/presenter/album_list"
require "picasa/presenter/author"
require "picasa/presenter/comment"
require "picasa/presenter/comment_list"
require "picasa/presenter/content"
require "picasa/presenter/link"
require "picasa/presenter/media"
require "picasa/presenter/photo"
require "picasa/presenter/tag"
require "picasa/presenter/tag_list"
require "picasa/presenter/thumbnail"
